FROM ubuntu:22.04

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8
ENV POETRY_VERSION=1.5.1

WORKDIR /

#BASIC
RUN apt-get update && apt-get install -y iputils-ping 
RUN apt-get install -y curl
RUN apt-get install -y iproute2
RUN apt-get install -y wget
RUN apt-get install -y gnupg
RUN apt-get install -y openssh-server
RUN apt-get install -y git
RUN apt-get install -y sshpass

ENV RUNNER_ALLOW_RUNASROOT 1

RUN mkdir actions-runner && cd actions-runner
WORKDIR /actions-runner
RUN curl -o actions-runner-linux-x64-2.317.0.tar.gz -L https://github.com/actions/runner/releases/download/v2.317.0/actions-runner-linux-x64-2.317.0.tar.gz
RUN echo "9e883d210df8c6028aff475475a457d380353f9d01877d51cc01a17b2a91161d  actions-runner-linux-x64-2.317.0.tar.gz" | shasum -a 256 -c
RUN tar xzf ./actions-runner-linux-x64-2.317.0.tar.gz

WORKDIR /code

# RUN curl -sSL https://install.python-poetry.org | python3 -
# ENV PATH="${PATH}:/root/.local/bin"